name: ArmoredPets
main: me.ventan.ArmoredPets.MainArmoredPets
version: 1.0
author: Ventan
website: www.servernet.pl
description: Plugin na pety
depend: [Citizens]
softdepend: [PlaceholderAPI]
commands:
  spawnPet:
    description: Spawni peta ktory za TB chodzi
    permission: armoredpets.spawn
  despawnPet:
    description:  Usuwa peta i daje go do ręki
  zalozPet:
    description: Zaklada peta z ekwipunku
  spawnPetNpc:
    description: spawni npc który weryfikuje peta
    permission: armoredpets.spawnNPC
  removePetNpc:
    description: usuwa npc który weryfikuje peta
    permission: armoredpets.spawnNPC
  spawnNpcHelper:
    description: spawnuje helper do testowania zoologa
    permission: armoredpets.spawnhelper